name = "distro-shill"
main = "src/index.ts"
compatibility_date = "2025-01-26"

assets = { directory = "public" }
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "Distro"
database_id = "e8a24658-7ffe-45bb-a5dd-7728f0188c90"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"


# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
